apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: peercode-question-service
  name: peercode-question-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peercode-question-service
  template:
    metadata:
      labels:
        io.kompose.network/network: "true"
        app: peercode-question-service
    spec:
      containers:
      - name: peercode-question-service
        image: public.ecr.aws/a6n0p1z7/peercode-test:latest-peercode-question-service
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: KAFKA_GROUP_QUESTION_SERVICE
          value: kafka_group_question_service
        - name: KAFKA_SERVER_NAME
          value: peercode-kafka:19092
        - name: KAFKA_TOPICS
          value: errors,users,question_service,question_bank,question_of_the_day
        - name: KAFKA_TOPIC_QUESTION_BANK
          value: question_bank
        - name: KAFKA_TOPIC_QUESTION_OF_THE_DAY
          value: question_of_the_day
        - name: KAFKA_TOPIC_QUESTION_SERVICE
          value: question_service
        - name: MONGO_PEERCODE_DATABASE_NAME
          valueFrom:
              secretKeyRef:
                name: secret
                key: MONGO_PEERCODE_DATABASE_NAME
        - name: MONGO_PEERCODE_DATABASE_PASSWORD
          valueFrom:
              secretKeyRef:
                name: secret
                key: MONGO_PEERCODE_DATABASE_PASSWORD
        - name: MONGO_PEERCODE_DATABASE_USER
          valueFrom:
              secretKeyRef:
                name: secret
                key: MONGO_PEERCODE_DATABASE_USER
        - name: MONGO_PEERCODE_HOST_NAME
          valueFrom:
              secretKeyRef:
                name: secret
                key: MONGO_PEERCODE_HOST_NAME
        - name: MONGO_PEERCODE_URL
          valueFrom:
              secretKeyRef:
                name: secret
                key: MONGO_PEERCODE_URL
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: peercode-question-service
  name: peercode-question-service
spec:
  ports:
  - name: "5001"
    port: 5001
    targetPort: 5001
  selector:
    app: peercode-question-service
status:
