apiVersion: apps/v1
kind: Deployment
metadata:
  name: peercode-kafka
  labels:
    app: peercode-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peercode-kafka
  template:
    metadata:
      labels:
        app: peercode-kafka
    spec:
      containers:
      - name: peercode-kafka
        image: confluentinc/cp-kafka:7.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9092
        - containerPort: 19092
        env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://peercode-kafka:9092,PLAINTEXT_INTERNAL://broker:29092,PLAINTEXT_HOST://peercode-kafka:19092
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: peercode-zookeeper:2181
        
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: peercode-kafka
  labels:
    app: peercode-kafka
spec:
  type: NodePort
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  - name: "19092"
    port: 19092
    targetPort: 19092
  selector:
    app: peercode-kafka
status:
  loadBalancer: {}
