name: Build and Deploy React App

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 

      - name: Change directory to frontend
        run: cd frontend

      - name: Install frontend dependencies
        run: npm i

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements-dev.txt

      - name: Install other dependencies
        run: pip install -r requirements.txt

      - name: Run unittest
        run: npx jest