name: System Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 

      - name: Change directory to frontend
        run: cd frontend

      - name: Install frontend dependencies
        run: npm i

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements-dev.txt

      - name: Install other dependencies
        run: pip install -r requirements.txt

      - name: Build app
        run: docker-compose -f docker-compose.yml build &

      - name: Delay before running app
        run: sleep 60  

      - name: Run app
        run: bash start.sh &

      - name: Delay before running system tests
        run: sleep 60
        
      - name: Run system tests
        run: pytest
